[package]
name = "robopoker"
version = "0.1.1"
authors = ["Kelechi Ukah <ukahkelechi@gmail.com>"]
description = "Implementations of Meta's Pluribus No-Limit Texas Hold-Em solution."
homepage = "https://github.com/krukah/robopoker"
repository = "https://github.com/krukah/robopoker"
readme = "README.md"
keywords = ["poker", "cards", "cfr", "mcts", "holdem"]
license = "MIT"
edition = "2021"
members = [
    "examples/protter",
]

[dependencies]
colored = "2.0"
petgraph = "0.6.5"
dialoguer = "0.11.0"
rand = { version = "0.8.5", features = ["small_rng"] }
bytes = "1.0"
num_cpus = "1.16.0"
log = "0.4.22"
rayon = "1.10.0"
byteorder = "1.5.0"
indicatif = "0.17.8"
anyhow = "1.0.90"
serde = { version = "1.0.210", features = ["derive"] }
bincode = "1.3.3"
lz4_flex = { version = "0.11", default-features = false }
simplelog = "0.12.2"
lsh-rs = { git = "https://github.com/19h/lsh-rs", rev = "929b9b60455006815691cfc2a00564617e027443"}

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
plotters = "0.3"

[[bench]]
name = "benchmarks"
harness = false

[features]
default = []
shortdeck = []
